brew "tmux"
brew "neovim"
brew "fzf"
brew "exa"
brew "bat"
brew "fd"
brew "starship"
brew "aws-vault"
brew "ripgrep"
brew "direnv"
brew "reattach-to-user-namespace"
brew "git-delta"
brew "nvm"
brew "pyenv"
brew "jq"
brew "graphviz"
brew "postgresql@13"
brew "awscli"
brew "ffmpeg"
# tap "homebrew/cask-fonts"
# brew "font-hack-nerd-font"
brew "gnupg"
