source $HOME/.config/nvim/basic.vim
source $HOME/.config/nvim/plug.vim
source $HOME/.config/nvim/color.vim
source $HOME/.config/nvim/fzf.vim
source $HOME/.config/nvim/nerdtree.vim
source $HOME/.config/nvim/rooter.vim
source $HOME/.config/nvim/spelunker.vim
luafile $HOME/.config/nvim/lua/treesitter.lua
luafile $HOME/.config/nvim/lua/lsp.lua
luafile $HOME/.config/nvim/lua/my_cmp.lua
luafile $HOME/.config/nvim/lua/my_copilot.lua
