source $HOME/.config/nvim/general.vim
source $HOME/.config/nvim/plug.vim
source $HOME/.config/nvim/color.vim
source $HOME/.config/nvim/vimspector.vim
source $HOME/.config/nvim/rust.vim
source $HOME/.config/nvim/coc.vim
source $HOME/.config/nvim/treesitter.vim
source $HOME/.config/nvim/fzf.vim
source $HOME/.config/nvim/nerdtree.vim
source $HOME/.config/nvim/rooter.vim
